# Generated by Django 4.1.1 on 2022-09-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='post_date',
            new_name='date_time',
        ),
    ]
